In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
datasets=pd.read_csv('Churn/Customer_Churn.csv')

In [14]:
datasets.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [15]:
datasets['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [16]:
datasets['MultipleLines']=datasets['MultipleLines'].replace({'No phone service' : 'No'})

In [17]:
datasets['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [18]:
columns=['OnlineBackup','DeviceProtection','StreamingMovies','OnlineSecurity','StreamingTV','OnlineSecurity']

for i in columns:
    datasets[i]=datasets[i].replace({'No internet service' :'No'})

In [19]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
customerID          7043 non-null object
gender              7043 non-null object
SeniorCitizen       7043 non-null int64
Partner             7043 non-null object
Dependents          7043 non-null object
tenure              7043 non-null int64
PhoneService        7043 non-null object
MultipleLines       7043 non-null object
InternetService     7043 non-null object
OnlineSecurity      7043 non-null object
OnlineBackup        7043 non-null object
DeviceProtection    7043 non-null object
TechSupport         7043 non-null object
StreamingTV         7043 non-null object
StreamingMovies     7043 non-null object
Contract            7043 non-null object
PaperlessBilling    7043 non-null object
PaymentMethod       7043 non-null object
MonthlyCharges      7043 non-null float64
TotalCharges        7043 non-null object
Churn               7043 non-null object
dtypes: float64(1), int64(2), obj

In [20]:
datasets['TotalCharges']=datasets['TotalCharges'].replace(" ",np.nan)

In [21]:
datasets=datasets[datasets['TotalCharges'].notnull()]

In [22]:
datasets.shape

(7032, 21)

In [23]:
data=datasets.columns

In [24]:
for i in data:
    print(i,datasets[i].unique())

customerID ['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' ... '4801-JZAZL' '8361-LTMKD'
 '3186-AJIEK']
gender ['Female' 'Male']
SeniorCitizen [0 1]
Partner ['Yes' 'No']
Dependents ['No' 'Yes']
tenure [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26 39]
PhoneService ['No' 'Yes']
MultipleLines ['No' 'Yes']
InternetService ['DSL' 'Fiber optic' 'No']
OnlineSecurity ['No' 'Yes']
OnlineBackup ['Yes' 'No']
DeviceProtection ['No' 'Yes']
TechSupport ['No' 'Yes' 'No internet service']
StreamingTV ['No' 'Yes']
StreamingMovies ['No' 'Yes']
Contract ['Month-to-month' 'One year' 'Two year']
PaperlessBilling ['Yes' 'No']
PaymentMethod ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
TotalCharges ['29.85' '1889.5' '108.15' ... '346.45' '306.6' '68

In [25]:
datasets['TechSupport']=datasets['TechSupport'].replace({'No internet service' : 'No'})

In [26]:
len(datasets.columns)

21

In [27]:
datasets=datasets.reset_index()[datasets.columns]

In [28]:
datasets['TotalCharges']=datasets['TotalCharges'].astype(float)

In [29]:
datasets.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [30]:
datasets['gender']=datasets['gender'].replace({'Male':1,'Female':0})

In [31]:
from sklearn.preprocessing import LabelEncoder

In [32]:
label_encoder=LabelEncoder()

In [33]:
datasets['Partner']=datasets['Partner'].replace({'Yes':1,'No':0})

In [34]:
datasets['Dependents']=label_encoder.fit_transform(datasets['Dependents'])

In [35]:
datasets['Dependents'].unique()

array([0, 1], dtype=int64)

In [36]:
datasets['PhoneService']=datasets['PhoneService'].replace({'Yes':1,'No':0})

In [37]:
datasets['PhoneService'].unique()

array([0, 1], dtype=int64)

In [38]:
datasets['MultipleLines']=datasets['MultipleLines'].replace({'Yes':1,'No':0})

In [39]:
datasets['MultipleLines'].unique()

array([0, 1], dtype=int64)

In [40]:
datasets.shape

(7032, 21)

In [41]:
datasets.corr()

gender  SeniorCitizen   Partner  Dependents    tenure  \
gender          1.000000      -0.001819 -0.001379    0.010349  0.005285   
SeniorCitizen  -0.001819       1.000000  0.016957   -0.210550  0.015683   
Partner        -0.001379       0.016957  1.000000    0.452269  0.381912   
Dependents      0.010349      -0.210550  0.452269    1.000000  0.163386   
tenure          0.005285       0.015683  0.381912    0.163386  1.000000   
PhoneService   -0.007515       0.008392  0.018397   -0.001078  0.007877   
MultipleLines  -0.008883       0.142996  0.142561   -0.024307  0.332399   
MonthlyCharges -0.013779       0.219874  0.097825   -0.112343  0.246862   
TotalCharges    0.000048       0.102411  0.319072    0.064653  0.825880   

                PhoneService  MultipleLines  MonthlyCharges  TotalCharges  
gender             -0.007515      -0.008883       -0.013779      0.000048  
SeniorCitizen       0.008392       0.142996        0.219874      0.102411  
Partner             0.018397       0.142561        0.097825      0.319072  
Dependents         -0.001078      -0.024307       -0.112343      0.064653  
tenure              0.007877       0.332399        0.246862      0.825880  
PhoneService        1.000000       0.279530        0.248033      0.113008  
MultipleLines       0.279530       1.000000        0.490912      0.469042  
MonthlyCharges      0.248033       0.490912        1.000000      0.651065  
TotalCharges        0.113008       0.469042        0.651065      1.000000

In [42]:
datasets['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [43]:
datasets['InternetService']=datasets['InternetService'].replace({'DSL' : 1,'Fiber optic' : 2 ,'No' : 0})

In [44]:
datasets['OnlineSecurity'].unique()

array(['No', 'Yes'], dtype=object)

In [45]:
datasets['OnlineSecurity']=datasets['OnlineSecurity'].replace({'Yes':1,'No':0})

In [46]:
datasets['OnlineBackup'].unique()

array(['Yes', 'No'], dtype=object)

In [47]:
datasets['OnlineBackup']=datasets['OnlineBackup'].replace({'Yes':1,'No':0})

In [48]:
datasets['DeviceProtection'].unique()

array(['No', 'Yes'], dtype=object)

In [49]:
datasets['DeviceProtection']=datasets['DeviceProtection'].replace({'Yes':1,'No':0})

In [50]:
datasets['TechSupport']=datasets['TechSupport'].replace({'Yes':1,'No':0})

In [51]:
datasets['TechSupport'].unique()

array([0, 1], dtype=int64)

In [52]:
datasets['PaymentMethod'].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [53]:
columns=['StreamingTV','StreamingMovies','PaperlessBilling']

for i in columns:
    datasets[i]=datasets[i].replace({'Yes':1,'No':0})

In [54]:
datasets['Contract'].unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [55]:
datasets['Contract']=datasets['Contract'].replace({'Month-to-month' : 0,'One year':1, 'Two year':2})

In [56]:
datasets['Contract'].unique()

array([0, 1, 2], dtype=int64)

In [57]:
datasets=datasets.drop(['PaymentMethod'],axis='columns')

In [58]:
from sklearn.preprocessing import StandardScaler
standard=StandardScaler()
columns_for_fitting=['tenure','MonthlyCharges','TotalCharges']

datasets[columns_for_fitting]=standard.fit_transform(datasets[columns_for_fitting])

In [59]:
datasets.corr()

gender  SeniorCitizen   Partner  Dependents    tenure  \
gender            1.000000      -0.001819 -0.001379    0.010349  0.005285   
SeniorCitizen    -0.001819       1.000000  0.016957   -0.210550  0.015683   
Partner          -0.001379       0.016957  1.000000    0.452269  0.381912   
Dependents        0.010349      -0.210550  0.452269    1.000000  0.163386   
tenure            0.005285       0.015683  0.381912    0.163386  1.000000   
PhoneService     -0.007515       0.008392  0.018397   -0.001078  0.007877   
MultipleLines    -0.008883       0.142996  0.142561   -0.024307  0.332399   
InternetService  -0.009643       0.259030  0.000938   -0.177789  0.031272   
OnlineSecurity   -0.016328      -0.038576  0.143346    0.080786  0.328297   
OnlineBackup     -0.013093       0.066663  0.141849    0.023639  0.361138   
DeviceProtection -0.000807       0.059514  0.153556    0.013900  0.361520   
TechSupport      -0.008507      -0.060577  0.120206    0.063053  0.325288   
StreamingTV      -0.007124       0.105445  0.124483   -0.016499  0.280264   
StreamingMovies  -0.010105       0.119842  0.118108   -0.038375  0.285402   
Contract          0.000095      -0.141820  0.294094    0.240556  0.676734   
PaperlessBilling -0.011902       0.156258 -0.013957   -0.110131  0.004823   
MonthlyCharges   -0.013779       0.219874  0.097825   -0.112343  0.246862   
TotalCharges      0.000048       0.102411  0.319072    0.064653  0.825880   

                  PhoneService  MultipleLines  InternetService  \
gender               -0.007515      -0.008883        -0.009643   
SeniorCitizen         0.008392       0.142996         0.259030   
Partner               0.018397       0.142561         0.000938   
Dependents           -0.001078      -0.024307        -0.177789   
tenure                0.007877       0.332399         0.031272   
PhoneService          1.000000       0.279530         0.094182   
MultipleLines         0.279530       1.000000         0.345068   
InternetService       0.094182       0.345068         1.000000   
OnlineSecurity       -0.091676       0.098592         0.156493   
OnlineBackup         -0.052133       0.202228         0.307223   
DeviceProtection     -0.070076       0.201733         0.313420   
TechSupport          -0.095138       0.100421         0.164532   
StreamingTV          -0.021383       0.257804         0.429616   
StreamingMovies      -0.033477       0.259194         0.426820   
Contract              0.003019       0.107529        -0.288855   
PaperlessBilling      0.016696       0.163746         0.377644   
MonthlyCharges        0.248033       0.490912         0.905389   
TotalCharges          0.113008       0.469042         0.428212   

                  OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  \
gender                 -0.016328     -0.013093         -0.000807    -0.008507   
SeniorCitizen          -0.038576      0.066663          0.059514    -0.060577   
Partner                 0.143346      0.141849          0.153556     0.120206   
Dependents              0.080786      0.023639          0.013900     0.063053   
tenure                  0.328297      0.361138          0.361520     0.325288   
PhoneService           -0.091676     -0.052133         -0.070076    -0.095138   
MultipleLines           0.098592      0.202228          0.201733     0.100421   
InternetService         0.156493      0.307223          0.313420     0.164532   
OnlineSecurity          1.000000      0.283285          0.274875     0.354458   
OnlineBackup            0.283285      1.000000          0.303058     0.293705   
DeviceProtection        0.274875      0.303058          1.000000     0.332850   
TechSupport             0.354458      0.293705          0.332850     1.000000   
StreamingTV             0.175514      0.281601          0.389924     0.277549   
StreamingMovies         0.187426      0.274523          0.402309     0.280155   
Contract                0.245660      0.155262          0.219648     0.293967   
Paper

In [60]:
y=datasets['Churn']

In [61]:
X=datasets.drop(['Churn','customerID','gender','PhoneService','MultipleLines','OnlineBackup','StreamingMovies','StreamingTV'],axis='columns')

In [90]:
y.head()

0     No
1     No
2    Yes
3     No
4    Yes
Name: Churn, dtype: object

In [63]:
from sklearn.model_selection import  train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [64]:
from sklearn.metrics  import accuracy_score
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression()

log_model.fit(X_train,y_train)
y_pred1=log_model.predict(X_test)

print(round(accuracy_score(y_pred1,y_test)*100,2))

79.89


C:\Users\abhijeet\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [65]:
from sklearn.tree import DecisionTreeClassifier
tree_model=DecisionTreeClassifier()

tree_model.fit(X_train,y_train)
y_pred2=tree_model.predict(X_test)

print(round(accuracy_score(y_pred2,y_test)*100,2))

74.13


In [73]:
tree_model.feature_importances_

array([0.01976495, 0.02045773, 0.02167085, 0.12751835, 0.05914376,
       0.01920201, 0.02028837, 0.01793512, 0.1694265 , 0.02297753,
       0.25311011, 0.24850472])

In [74]:
X_train.columns

Index(['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'InternetService',
       'OnlineSecurity', 'DeviceProtection', 'TechSupport', 'Contract',
       'PaperlessBilling', 'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [75]:
from sklearn.svm import SVC
svc_model=SVC(kernel='rbf',random_state=50)

svc_model.fit(X_train,y_train)
y_pred3=svc_model.predict(X_test)

print(round(accuracy_score(y_pred3,y_test)*100,2))

C:\Users\abhijeet\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


79.46


In [76]:
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier(n_estimators=20,criterion='entropy',random_state=0)

rf_model.fit(X_train,y_train)
y_pred4=rf_model.predict(X_test)

print(round(accuracy_score(y_pred4,y_test)*100,2))

78.68


In [77]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier()

knn_model.fit(X_train,y_train)
y_pred5=knn_model.predict(X_test)

print(round(accuracy_score(y_pred5,y_test)*100,2))

78.46


In [78]:
from sklearn.metrics import confusion_matrix
cm_rf=confusion_matrix(y_pred4,y_test)
cm_rf

array([[930, 196],
       [104, 177]], dtype=int64)

In [79]:
datasets['Probablity_of_churn']=rf_model.predict_proba(datasets[X_test.columns])[:,1]

In [80]:
X.head()

SeniorCitizen  Partner  Dependents    tenure  InternetService  \
0              0        1           0 -1.280248                1   
1              0        0           0  0.064303                1   
2              0        0           0 -1.239504                1   
3              0        0           0  0.512486                1   
4              0        0           0 -1.239504                2   

   OnlineSecurity  DeviceProtection  TechSupport  Contract  PaperlessBilling  \
0               0                 0            0         0                 1   
1               1                 1            0         1                 0   
2               1                 0            0         0                 1   
3               1                 1            1         1                 0   
4               0                 0            0         0                 1   

   MonthlyCharges  TotalCharges  
0       -1.161694     -0.994194  
1       -0.260878     -0.173740  
2       -0.363923     -0.959649  
3       -0.747850     -0.195248  
4        0.196178     -0.940457

In [81]:
import pickle

In [82]:
pickle.dump(knn_model, open('model','wb')) 

In [83]:
model=pickle.load(open('model','rb') )

In [84]:
model.predict(X_test)

array(['Yes', 'Yes', 'Yes', ..., 'No', 'No', 'No'], dtype=object)

In [85]:
y_pred1

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [99]:
from lightgbm import LGBMClassifier
lgb=LGBMClassifier(n_estimators=100,learning_rate=0.1,random_state=42)
lgb.fit(X_train,y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [100]:
y_pred=lgb.predict(X_test)

In [103]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.7903340440653873

In [106]:
from catboost import CatBoostClassifier
cb=CatBoostClassifier()
cb.fit(X_train,y_train)

Learning rate set to 0.02154
0:	learn: 0.6793246	total: 53.7ms	remaining: 53.7s
1:	learn: 0.6649537	total: 57.2ms	remaining: 28.5s
2:	learn: 0.6515217	total: 60.5ms	remaining: 20.1s
3:	learn: 0.6388282	total: 63.8ms	remaining: 15.9s
4:	learn: 0.6265473	total: 67.1ms	remaining: 13.4s
5:	learn: 0.6153398	total: 70.3ms	remaining: 11.7s
6:	learn: 0.6050507	total: 73.3ms	remaining: 10.4s
7:	learn: 0.5955475	total: 76.7ms	remaining: 9.51s
8:	learn: 0.5865377	total: 79.8ms	remaining: 8.79s
9:	learn: 0.5779219	total: 83ms	remaining: 8.22s
10:	learn: 0.5701461	total: 86.2ms	remaining: 7.75s
11:	learn: 0.5618114	total: 89.5ms	remaining: 7.37s
12:	learn: 0.5544415	total: 92.9ms	remaining: 7.05s
13:	learn: 0.5477853	total: 96.1ms	remaining: 6.77s
14:	learn: 0.5415626	total: 99.3ms	remaining: 6.52s
15:	learn: 0.5355731	total: 103ms	remaining: 6.3s
16:	learn: 0.5304581	total: 106ms	remaining: 6.12s
17:	learn: 0.5249494	total: 109ms	remaining: 5.95s
18:	learn: 0.5199760	total: 112ms	remaining: 5.81s


185:	learn: 0.3987571	total: 684ms	remaining: 2.99s
186:	learn: 0.3986825	total: 688ms	remaining: 2.99s
187:	learn: 0.3985854	total: 692ms	remaining: 2.99s
188:	learn: 0.3984615	total: 696ms	remaining: 2.99s
189:	learn: 0.3983049	total: 702ms	remaining: 2.99s
190:	learn: 0.3981737	total: 705ms	remaining: 2.99s
191:	learn: 0.3980650	total: 709ms	remaining: 2.98s
192:	learn: 0.3978945	total: 712ms	remaining: 2.98s
193:	learn: 0.3978374	total: 715ms	remaining: 2.97s
194:	learn: 0.3976992	total: 719ms	remaining: 2.97s
195:	learn: 0.3975602	total: 722ms	remaining: 2.96s
196:	learn: 0.3974154	total: 725ms	remaining: 2.96s
197:	learn: 0.3972994	total: 729ms	remaining: 2.95s
198:	learn: 0.3972084	total: 732ms	remaining: 2.94s
199:	learn: 0.3970581	total: 735ms	remaining: 2.94s
200:	learn: 0.3969298	total: 739ms	remaining: 2.94s
201:	learn: 0.3968136	total: 742ms	remaining: 2.93s
202:	learn: 0.3966639	total: 745ms	remaining: 2.92s
203:	learn: 0.3965497	total: 748ms	remaining: 2.92s
204:	learn: 

375:	learn: 0.3802209	total: 1.37s	remaining: 2.28s
376:	learn: 0.3801289	total: 1.38s	remaining: 2.28s
377:	learn: 0.3800051	total: 1.38s	remaining: 2.28s
378:	learn: 0.3798585	total: 1.39s	remaining: 2.27s
379:	learn: 0.3797688	total: 1.39s	remaining: 2.27s
380:	learn: 0.3796757	total: 1.4s	remaining: 2.27s
381:	learn: 0.3796053	total: 1.4s	remaining: 2.27s
382:	learn: 0.3795065	total: 1.41s	remaining: 2.27s
383:	learn: 0.3794245	total: 1.41s	remaining: 2.26s
384:	learn: 0.3792920	total: 1.41s	remaining: 2.26s
385:	learn: 0.3791571	total: 1.42s	remaining: 2.26s
386:	learn: 0.3790499	total: 1.43s	remaining: 2.26s
387:	learn: 0.3789619	total: 1.44s	remaining: 2.27s
388:	learn: 0.3788944	total: 1.44s	remaining: 2.27s
389:	learn: 0.3787709	total: 1.45s	remaining: 2.26s
390:	learn: 0.3786341	total: 1.45s	remaining: 2.26s
391:	learn: 0.3784251	total: 1.46s	remaining: 2.26s
392:	learn: 0.3783158	total: 1.47s	remaining: 2.27s
393:	learn: 0.3781475	total: 1.5s	remaining: 2.3s
394:	learn: 0.37

542:	learn: 0.3630276	total: 2.01s	remaining: 1.69s
543:	learn: 0.3629419	total: 2.01s	remaining: 1.69s
544:	learn: 0.3628727	total: 2.02s	remaining: 1.68s
545:	learn: 0.3627525	total: 2.02s	remaining: 1.68s
546:	learn: 0.3626974	total: 2.03s	remaining: 1.68s
547:	learn: 0.3626003	total: 2.03s	remaining: 1.67s
548:	learn: 0.3625073	total: 2.03s	remaining: 1.67s
549:	learn: 0.3623938	total: 2.04s	remaining: 1.67s
550:	learn: 0.3623031	total: 2.04s	remaining: 1.66s
551:	learn: 0.3621912	total: 2.04s	remaining: 1.66s
552:	learn: 0.3621284	total: 2.05s	remaining: 1.65s
553:	learn: 0.3620275	total: 2.05s	remaining: 1.65s
554:	learn: 0.3619074	total: 2.05s	remaining: 1.65s
555:	learn: 0.3618054	total: 2.06s	remaining: 1.64s
556:	learn: 0.3617017	total: 2.06s	remaining: 1.64s
557:	learn: 0.3615963	total: 2.06s	remaining: 1.63s
558:	learn: 0.3614954	total: 2.07s	remaining: 1.63s
559:	learn: 0.3614009	total: 2.07s	remaining: 1.63s
560:	learn: 0.3613027	total: 2.07s	remaining: 1.62s
561:	learn: 

742:	learn: 0.3447884	total: 2.69s	remaining: 932ms
743:	learn: 0.3446822	total: 2.7s	remaining: 929ms
744:	learn: 0.3446040	total: 2.7s	remaining: 925ms
745:	learn: 0.3445083	total: 2.71s	remaining: 921ms
746:	learn: 0.3444608	total: 2.71s	remaining: 917ms
747:	learn: 0.3443150	total: 2.71s	remaining: 914ms
748:	learn: 0.3442134	total: 2.72s	remaining: 910ms
749:	learn: 0.3441418	total: 2.72s	remaining: 907ms
750:	learn: 0.3440638	total: 2.72s	remaining: 903ms
751:	learn: 0.3440031	total: 2.73s	remaining: 900ms
752:	learn: 0.3439176	total: 2.73s	remaining: 896ms
753:	learn: 0.3438084	total: 2.73s	remaining: 892ms
754:	learn: 0.3437054	total: 2.74s	remaining: 889ms
755:	learn: 0.3436481	total: 2.74s	remaining: 885ms
756:	learn: 0.3436021	total: 2.75s	remaining: 881ms
757:	learn: 0.3435548	total: 2.75s	remaining: 878ms
758:	learn: 0.3434587	total: 2.75s	remaining: 874ms
759:	learn: 0.3433796	total: 2.75s	remaining: 870ms
760:	learn: 0.3433174	total: 2.76s	remaining: 866ms
761:	learn: 0.

941:	learn: 0.3290721	total: 3.38s	remaining: 208ms
942:	learn: 0.3289085	total: 3.38s	remaining: 205ms
943:	learn: 0.3287939	total: 3.39s	remaining: 201ms
944:	learn: 0.3286943	total: 3.39s	remaining: 197ms
945:	learn: 0.3286012	total: 3.4s	remaining: 194ms
946:	learn: 0.3285197	total: 3.4s	remaining: 190ms
947:	learn: 0.3284857	total: 3.4s	remaining: 187ms
948:	learn: 0.3284291	total: 3.41s	remaining: 183ms
949:	learn: 0.3282953	total: 3.41s	remaining: 180ms
950:	learn: 0.3282173	total: 3.41s	remaining: 176ms
951:	learn: 0.3281500	total: 3.42s	remaining: 172ms
952:	learn: 0.3280345	total: 3.42s	remaining: 169ms
953:	learn: 0.3279458	total: 3.42s	remaining: 165ms
954:	learn: 0.3278527	total: 3.43s	remaining: 162ms
955:	learn: 0.3277891	total: 3.43s	remaining: 158ms
956:	learn: 0.3277044	total: 3.43s	remaining: 154ms
957:	learn: 0.3275776	total: 3.44s	remaining: 151ms
958:	learn: 0.3274647	total: 3.44s	remaining: 147ms
959:	learn: 0.3273605	total: 3.44s	remaining: 144ms
960:	learn: 0.3

In [107]:
y_pred=cb.predict(X_test)

In [108]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.8017057569296375

In [110]:
import sklearn
sklearn.__version__

'0.21.3'

In [1]:
X

NameError: name 'X' is not defined